# Generated by Django 4.2.4 on 2023-09-07 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='weightAvg',
        ),
    ]
