# Generated by Django 4.2.4 on 2024-01-22 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_user_address_alter_user_numberphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='isComplete',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='isDisable',
        ),
        migrations.AddField(
            model_name='trip',
            name='canceledDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='deleteDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
