# Generated by Django 4.2.4 on 2023-08-29 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_enddatecompany_alter_trip_enddatecustomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.truck'),
        ),
    ]
