# Generated by Django 4.2.4 on 2024-01-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_iscomplete_remove_trip_isdisable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='canceledDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='deleteDate',
            field=models.DateField(null=True),
        ),
    ]
