# Generated by Django 4.2.4 on 2023-09-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_truck_isdisable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAssignedTruckDisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.truck')),
            ],
            options={
                'db_table': 'trips_truck_disable',
            },
        ),
    ]
